name: Build and publish docker images when release is published

on:
  release:
    types: [ published ]

jobs:
  Build-and-publish-docker-images:
    runs-on: ubuntu-latest
    if: github.repository == 'eclipse-aaspe/server'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: adminshellio
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and publish AasxServerBlazor
        uses: docker/build-push-action@v6
        with:
          push: true
          load: true
          file: ./src/docker/Dockerfile-AasxServerBlazor
          tags: adminshellio/aasx-server-blazor-for-demo:latest

      - name: Build and publish AasxServerBlazor-arm32
        uses: docker/build-push-action@v6
        with:
          push: true
          load: true
          file: ./src/docker/Dockerfile-AasxServerBlazor-arm32
          tags: adminshellio/aasx-server-blazor-for-demo-arm32:latest

      - name: Build and publish AasxServerBlazor-arm64
        uses: docker/build-push-action@v6
        with:
          push: true
          load: true
          file: ./src/docker/Dockerfile-AasxServerBlazor-arm64
          tags: adminshellio/aasx-server-blazor-for-demo-arm64:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and publish AasxServerCore
        uses: docker/build-push-action@v6
        with:
          push: true
          load: true
          file: ./src/docker/Dockerfile-AasxServerAspNetCore
          tags: adminshellio/aasx-server-aspnetcore-for-demo:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish AasxServerCore-arm32
        uses: docker/build-push-action@v6
        with:
          push: true
          load: true
          file: ./src/docker/Dockerfile-AasxServerAspNetCore-arm32
          tags: adminshellio/aasx-server-aspnetcore-for-demo-arm32:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish AasxServerCore-arm64
        uses: docker/build-push-action@v6
        with:
          push: true
          load: true
          file: ./src/docker/Dockerfile-AasxServerAspNetCore-arm64
          tags: adminshellio/aasx-server-aspnetcore-for-demo-arm64:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}"

