name: Check-style-workflow

on:
  pull_request:
    branches:
      - main
      - release
      - 'integration/**'
    types: [opened, synchronize, reopened, edited]
  push:
    branches:
      - main
      - release
      - 'integration/**'

jobs:
  Check-style:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET tools
        working-directory: src
        run: dotnet tool restore

      - name: Check code format
        working-directory: src
        run: powershell .\CheckFormat.ps1
