name: Check-release-workflow

on:
  pull_request:
    branches:
      - main
      - release
      - *
    types: [ opened, synchronize, reopened, edited ]

  push:
    branches:
      - main
      - release

jobs:
  Check-release:
    runs-on: windows-latest
    if: "!contains(github.event.pull_request.body, 'The workflow check-release was intentionally skipped.')"
    steps:
      - uses: actions/checkout@v3

      - name: Set timestamp
        id: setTimestamp
        run: |
          $timestamp = (Get-Date).ToString("yyyy-MM-ddTHH-mm-ssZ")
          if ($timestamp -match "'|\"|:")
          {
              throw "Unexpected characters in timestamp: $timestamp"
          }
          echo "::set-output name=timestamp::$timestamp"
        shell: pwsh

      - name: Install .NET Core 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      # Builds the project for release by executing the BuildForRelease.ps1 PowerShell script in the 'src' directory.
      - name: Build for release
        description:
        working-directory: src
        run: .\BuildForRelease.ps1
        shell: pwsh
      
      # Compares the output of the --help command with the README file to ensure consistency.
      - name: Package
        working-directory: src
        run: .\PackageRelease.ps1
        shell: pwsh
        with:
          suffix: alpha
      
      # Uploads the AasxServerBlazor artifact with a timestamp to the artifacts' repository.
      - name: Upload AasxServerBlazor
        uses: actions/upload-artifact@v3
        with:
          name: AasxServerBlazor.LATEST.alpha.${{ steps.setTimestamp.outputs.timestamp }}
          path: artefacts/release/LATEST.alpha/AasxServerBlazor.zip
      
      # Uploads the AasxServerAspNetCore artifact with a timestamp to the artifacts' repository.
      - name: Upload AasxServerAspNetCore
        uses: actions/upload-artifact@v3
        with:
          name: AasxServerAspNetCore.LATEST.alpha.${{ steps.setTimestamp.outputs.timestamp }}
          path: artefacts/release/LATEST.alpha/AasxServerAspNetCore.zip

      # Uncomment the following steps if you need to upload the AasxServerWindows artifact
      # - name: Upload AasxServerWindows
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: AasxServerWindows.LATEST.alpha.${{ steps.setTimestamp.outputs.timestamp }}
      #     path: artefacts/release/LATEST.alpha/AasxServerWindows.zip
