# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - AasxServerBlazor

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: aasxserverblazor
  AZURE_WEBAPP_PACKAGE_PATH: 'src' # Set this to the path to your web app project, defaults to the repository root:
  DOTNET_VERSION: '5.0.301' # The .NET SDK version to use

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -r linux-x64 --self-contained true /p:UseAppHost=true
    - name: Test
      run: |
        dotnet test --no-restore --verbosity normal

    - uses: azure/webapps-deploy@v2
      name: Deploy
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c4d452d1e22c438892c2f8f145f03761 }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'